# Generated by Django 3.0.3 on 2020-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=255, verbose_name='Name Role')),
                ('kode_role', models.CharField(max_length=20, verbose_name='Kode Role')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.CharField(choices=[('Active', 'A'), ('NotActive', 'N')], default='A', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('usercreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
